'use client'

import { useMemo, useState } from 'react'
import { Check, ChevronDown, Compass, Crosshair, Heart, MapPin, Plus, Search, Sparkles, Utensils, Waves, X } from 'lucide-react'

const gems = [
  { id: 1, name: 'Flamingo Watch Point', type: 'Nature', distance: '6 km', score: 91, x: '18%', y: '38%', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HwDu81xYApDJDC7k8jcK06XswyWust.png', tags: ['Bird Watching', 'Photography'], blurb: 'A peaceful bird watching spot with flamingos in season. Less crowded and perfect for nature lovers.' },
  { id: 2, name: 'Kharghar Hills', type: 'Nature', distance: '14 km', score: 89, x: '36%', y: '18%', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85', tags: ['Hiking', 'Views'], blurb: 'A green escape above the city with quiet trails and wide-open views.' },
  { id: 3, name: 'Belapur Fort', type: 'Heritage', distance: '12 km', score: 86, x: '58%', y: '26%', image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=85', tags: ['Heritage', 'History'], blurb: 'A compact historic fort where layers of the old port city meet the modern skyline.' },
  { id: 4, name: 'Shirvane Waterfall', type: 'Adventure', distance: '22 km', score: 84, x: '61%', y: '70%', image: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=900&q=85', tags: ['Waterfall', 'Adventure'], blurb: 'A cool monsoon trail ending at a tucked-away cascade.' },
]
const experiences = [
  ['Traditional Pottery Workshop', 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80', 'Nerul · 3 km', '₹500 · 2 hrs'],
  ['Koli Village Experience', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80', 'Diwale · 6 km', '₹400 · 2 hrs'],
  ['Local Food Walk', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', 'CBD Belapur · 5 km', '₹350 · 2.5 hrs'],
  ['Heritage Story Walk', 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=600&q=80', 'Belapur · 12 km', '₹450 · 2 hrs'],
]

export default function DiscoverPage() {
  const [active, setActive] = useState('All')
  const [selected, setSelected] = useState(gems[0])
  const [saved, setSaved] = useState(false)
  const [trip, setTrip] = useState(false)
  const [radius, setRadius] = useState('50 km')
  const [toast, setToast] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2200) }
  const filtered = useMemo(() => active === 'All' ? gems : gems.filter((gem) => gem.type === active), [active])
  const select = (gem: typeof gems[number]) => setSelected(gem)

  return <main className="discover-page">
    <div className="prototype-ribbon">Example prototype · product workflow preview</div>
    <header className="discover-header"><a className="discover-brand" href="/"><span className="discover-mark"><Compass size={22} /></span><span><strong>Hidden India</strong><small>Discover the India tourists don&apos;t see</small></span></a><nav><a className="active" href="#near-me">Discover Near Me</a><a href="#explore">Explore</a><a href="#experiences">Experiences</a><a href="#plan">Plan My Trip</a><a href="#events">Events</a><a href="#saved">Saved</a></nav><div className="discover-user"><MapPin size={16} /> Navi Mumbai <ChevronDown size={14} /><span className="user-avatar">AS</span></div></header>
    <section className="discover-shell" id="near-me">
      <aside className="filter-rail"><p className="rail-label">Your Location</p><button className="location-button"><strong>Near D.Y. Patil College</strong><span>Nerul, Navi Mumbai</span><Crosshair size={20} /></button><div className="rail-section"><p>Search Radius</p><div className="choice-grid">{['10 km', '25 km', '50 km', '100 km'].map((item) => <button className={radius === item ? 'chosen' : ''} onClick={() => setRadius(item)} key={item}>{item}</button>)}</div></div><div className="rail-section"><p>I&apos;m interested in</p><div className="interest-options">{[['Culture', Compass], ['Nature', Waves], ['Food', Utensils], ['Photography', Search], ['Adventure', Sparkles], ['More', Plus]].map(([label, Icon]) => <button key={label as string} onClick={() => setActive(label === 'More' ? 'All' : label as string)} className={active === label ? 'chosen' : ''}><Icon size={19} /><span>{label as string}</span></button>)}</div></div><div className="rail-section"><p>Time I have</p><div className="choice-grid">{['2 hrs', '4 hrs', '6 hrs', '1 Day'].map((item, i) => <button className={i === 1 ? 'chosen' : ''} key={item}>{item}</button>)}</div></div><div className="rail-section"><p>Budget (per person)</p><div className="choice-grid">{['₹200', '₹500', '₹1000', '₹1500+'].map((item, i) => <button className={i === 1 ? 'chosen' : ''} key={item}>{item}</button>)}</div></div><button className="discover-button" onClick={() => notify('Your hidden gems are ready')}><Sparkles size={16} /> Discover Hidden Gems</button></aside>
      <div className="discover-main"><div className="results-heading"><div><p className="prototype-kicker">Example discovery flow</p><h1>We found <em>{filtered.length} hidden gems</em> near you</h1><div className="legend-chips"><span>● Low Crowds</span><span>✦ High Culture</span><span>◉ Local Experiences</span></div></div><button className="view-select">Map View <ChevronDown size={15} /></button></div><div className="map-workspace"><div className="map-texture"><div className="water-shape" /><span className="map-city city-one">Navi Mumbai</span><span className="map-city city-two">Nerul</span><span className="map-city city-three">Belapur</span><div className="current-location"><span /></div>{filtered.map((gem) => <button key={gem.id} className={`gem-marker ${selected.id === gem.id ? 'active' : ''}`} style={{ left: gem.x, top: gem.y }} onClick={() => select(gem)} aria-label={`Select ${gem.name}`}><MapPin size={20} /><span>{gem.name}</span><small>{gem.distance}</small></button>)}<button className="recenter" onClick={() => notify('Map centred on your location')}><Crosshair size={18} /></button></div><div className="map-toolbar"><span>Hidden Score <ChevronDown size={13} /></span><span>Distance</span><span>Travel Time</span><span>Budget</span><span>Crowd Level</span></div></div><section className="strip-section"><div className="strip-heading"><h2>More hidden gems you might love</h2><button onClick={() => setActive('All')}>View all <ChevronDown size={14} /></button></div><div className="gem-strip">{gems.map((gem) => <button className="gem-card" key={gem.id} onClick={() => select(gem)}><img src={gem.image} alt="" /><span className="score">✦ {gem.score}</span><strong>{gem.name}</strong><small>{gem.distance} away</small><em>{gem.type}</em></button>)}</div></section><section className="strip-section" id="experiences"><div className="strip-heading"><h2>Local experiences near you</h2><button>View all <ChevronDown size={14} /></button></div><div className="experience-strip">{experiences.map(([name, image, place, price]) => <article key={name}><img src={image} alt="" /><button className="heart" aria-label={`Save ${name}`}><Heart size={16} /></button><strong>{name}</strong><small>{place}</small><small>{price}</small></article>)}</div></section></div>
      <aside className="detail-rail"><article className="selected-card"><div className="selected-image"><img src={selected.image} alt={selected.name} /><span>✦ Top Pick</span><button onClick={() => { setSaved(!saved); notify(saved ? 'Removed from saved' : 'Saved place') }} aria-label="Save place"><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="selected-content"><div className="selected-title"><h2>{selected.name}</h2><strong>{selected.score}/100<small>Hidden Score</small></strong></div><p><MapPin size={14} /> Nerul Lake, Navi Mumbai · {selected.distance} from you</p><div className="tags"><span>{selected.type}</span>{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="why"><strong>✦ Why we recommend this?</strong><p>{selected.blurb}</p></div><div className="facts"><span>♧<b>Low</b><small>Crowd Level</small></span><span>☼<b>6 AM – 9 AM</b><small>Best Time</small></span><span>◷<b>60 – 90 mins</b><small>Time Needed</small></span><span>₹<b>₹0 – ₹100</b><small>Budget</small></span></div><div className="detail-actions"><button className="discover-button" onClick={() => notify(`Opening details for ${selected.name}`)}>Explore Details</button><button className="add-button" onClick={() => { setTrip(!trip); notify(trip ? 'Removed from trip' : 'Added to trip') }}>{trip ? <Check size={16} /> : <Plus size={16} />}{trip ? 'Added' : 'Add to Trip'}</button></div></div></article><article className="itinerary-card" id="plan"><div className="itinerary-heading"><div><p className="prototype-kicker">AI suggested itinerary</p><h2>3 hours around you</h2></div><Sparkles size={18} /></div>{[['08:00 AM', 'Start from D.Y. Patil College', 'blue'], ['08:15 AM', 'D.Y. Patil Botanical Garden', 'green'], ['09:15 AM', 'Flamingo Watch Point', 'purple'], ['10:30 AM', 'Diwale Jetty', 'orange'], ['11:30 AM', 'Local Food Experience', 'yellow']].map(([time, text, color]) => <div className="timeline-row" key={time}><time>{time}</time><i className={color} /><span>{text}<small>{text.includes('Start') ? '' : '(Explore & Learn)'}</small></span></div>)}<div className="itinerary-total"><span>Total Time: <b>~3.5 hrs</b></span><span>Total Budget: <b>~₹450</b></span></div><button className="discover-button" onClick={() => notify('Full itinerary saved')}>View Full Plan</button></article></aside>
    </section>{toast && <div className="discover-toast"><Check size={15} /> {toast}</div>}<footer className="discover-footer"><span>◎ Low Tourist Crowds</span><span>♧ Support Local Communities</span><span>♜ Cultural & Natural Heritage</span><span>♢ Verified & Curated</span></footer><button className="prototype-close" onClick={() => window.location.href = '/'} aria-label="Return to main website"><X size={15} /> Return to main website</button>
  </main>
}
