'use client'

import { useMemo, useState } from 'react'
import {
  ArrowRight, Bookmark, Check, ChevronDown, Compass, Heart, MapPin,
  Menu, Plus, Search, Sparkles, Star, X, Zap,
} from 'lucide-react'

const places = [
  { id: 1, name: 'Khejarli', type: 'Heritage', distance: '28 km', image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=85', blurb: 'A quiet village where 363 Bishnoi people gave their lives to protect the khejri trees.', tags: ['Crafts', 'Heritage'], x: '30%', y: '37%' },
  { id: 2, name: 'Ranakpur Forest', type: 'Nature', distance: '41 km', image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=85', blurb: 'A green corridor of leopard country, marble temples, and slow village roads.', tags: ['Nature', 'Wildlife'], x: '66%', y: '27%' },
  { id: 3, name: 'Pipliyanagar', type: 'Food', distance: '62 km', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85', blurb: 'Join a family kitchen for smoky bajra rotis and recipes passed down seven generations.', tags: ['Food', 'Local life'], x: '51%', y: '62%' },
]

const filters = ['All places', 'Nature', 'Heritage', 'Food', 'Crafts']

export default function Page() {
  const [activeFilter, setActiveFilter] = useState('All places')
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<typeof places[number] | null>(null)
  const [saved, setSaved] = useState<number[]>([])
  const [trip, setTrip] = useState<number[]>([])
  const [showPrefs, setShowPrefs] = useState(false)
  const [toast, setToast] = useState('')

  const filtered = useMemo(() => places.filter((p) => activeFilter === 'All places' || p.tags.includes(activeFilter) || p.type === activeFilter).filter((p) => p.name.toLowerCase().includes(query.toLowerCase()) || p.blurb.toLowerCase().includes(query.toLowerCase())), [activeFilter, query])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const toggleSave = (id: number) => { setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); notify(saved.includes(id) ? 'Removed from saved places' : 'Saved to your collection') }
  const toggleTrip = (id: number) => { setTrip((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); notify(trip.includes(id) ? 'Removed from your trip' : 'Added to your trip') }

  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="site-header">
        <a className="brand" href="#top" aria-label="Hidden India home"><span className="brand-mark"><Compass size={19} /></span><span>hidden<span className="brand-accent">india</span></span></a>
        <nav className="desktop-nav" aria-label="Primary navigation"><a href="#explore">Explore</a><a href="#stories">Stories</a><a href="#about">About</a></nav>
        <div className="header-actions"><button className="icon-button" aria-label="Saved places" onClick={() => notify(`${saved.length} saved place${saved.length === 1 ? '' : 's'}`)}><Bookmark size={18} /><span>{saved.length || ''}</span></button><button className="outline-button" onClick={() => setShowPrefs(true)}>Set your compass <ArrowRight size={16} /></button><button className="mobile-menu" aria-label="Open menu"><Menu size={20} /></button></div>
      </header>

      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Travel beneath the surface</p><h1>Go where the<br /><em>stories</em> are.</h1><p className="hero-text">Discover the India that lives between the landmarks — shaped by local hands, seasonal light, and generations of belonging.</p><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try ‘a quiet place near the Aravallis’" aria-label="Search places" /><button onClick={() => notify(query ? `Exploring ${query}` : 'Try a destination, feeling, or region')}><ArrowRight size={18} /></button></div><div className="hero-meta"><span><span className="pulse" /> Curated by local voices</span><span>•</span><span>Punjab · Rajasthan · Himachal</span></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1100&q=85" alt="A winding road through golden desert hills" /><div className="hero-art-caption"><span>THE UNFAMILIAR INDIA</span><strong>There is more to see.</strong></div></div></section>

      <section className="explore-section" id="explore"><div className="section-heading"><div><p className="eyebrow">01 / Find your way</p><h2>Start with a feeling.</h2></div><button className="text-link" onClick={() => setShowPrefs(true)}>Personalise your map <ArrowRight size={15} /></button></div><div className="filter-row" role="group" aria-label="Place filters">{filters.map((filter) => <button key={filter} className={activeFilter === filter ? 'filter active' : 'filter'} onClick={() => setActiveFilter(filter)}>{filter}</button>)}<button className="filter distance">Within 100 km <ChevronDown size={14} /></button></div><div className="explore-grid"><div className="map-card"><div className="map-top"><span><MapPin size={15} /> Around Amritsar</span><span className="map-zoom">− &nbsp; +</span></div><div className="map-surface" aria-label="Stylized map of destinations around Amritsar"><div className="map-water" /><div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" /><div className="map-label label-one">AMRITSAR</div><div className="map-label label-two">BEAS</div><div className="user-pin"><span /></div>{filtered.map((place) => <button key={place.id} className={`map-pin ${selected?.id === place.id ? 'selected' : ''}`} style={{ left: place.x, top: place.y }} onClick={() => setSelected(place)} aria-label={`View ${place.name}`}><span>{place.id}</span></button>)}<div className="map-radius" /></div><div className="map-footer"><span><span className="legend-dot saffron" /> Your location</span><span><span className="legend-dot green" /> Hidden places</span><button onClick={() => notify('Map centred on your location')}>Recenter <MapPin size={14} /></button></div></div><aside className="recommendations"><div className="recommendation-title"><div><p className="eyebrow">Picked for you</p><h3>Worth the detour</h3></div><span className="ai-badge"><Sparkles size={13} /> AI</span></div>{filtered.map((place) => <article className="place-card" key={place.id} onClick={() => setSelected(place)}><img src={place.image} alt="" /><div className="place-card-content"><div className="place-card-top"><span className="place-type">{place.type}</span><button className={saved.includes(place.id) ? 'saved' : ''} onClick={(e) => { e.stopPropagation(); toggleSave(place.id) }} aria-label={`Save ${place.name}`}><Bookmark size={16} fill={saved.includes(place.id) ? 'currentColor' : 'none'} /></button></div><h4>{place.name}</h4><p>{place.blurb}</p><span className="distance-label"><MapPin size={12} /> {place.distance} away</span></div></article>)}{filtered.length === 0 && <p className="empty-state">No places match that search yet. Try a wider feeling.</p>}</aside></div></section>

      <section className="story-band" id="stories"><div><p className="eyebrow">02 / The why behind the where</p><h2>Not just places.<br /><em>Perspectives.</em></h2><p>Every recommendation has a reason. We connect you to the people, rituals, and landscapes that make a place worth the journey — not just the photograph.</p><button className="dark-button" onClick={() => notify('More stories coming soon')}>Read our approach <ArrowRight size={16} /></button></div><div className="quote-card"><div className="quote-mark">“</div><blockquote>Tourism should feel less like collecting places and more like being welcomed somewhere.</blockquote><div className="quote-author"><div className="avatar">A</div><span><strong>Anamika Singh</strong><small>Community host · Kangra Valley</small></span></div></div></section>

      <section className="lower-section" id="about"><div className="section-heading"><div><p className="eyebrow">03 / Make it yours</p><h2>Build a softer itinerary.</h2></div><button className="text-link" onClick={() => setShowPrefs(true)}>What are you into? <ArrowRight size={15} /></button></div><div className="interest-grid">{['Slow mornings', 'Local kitchens', 'Old stories', 'Wild places'].map((item, i) => <button key={item} className="interest-card" onClick={() => notify(`${item} added to your compass`)}><span className={`interest-image interest-${i + 1}`} /><span>{item}</span><ArrowRight size={16} /></button>)}</div><div className="trip-panel"><div><span className="trip-icon"><Zap size={17} /></span><div><p className="eyebrow">Your next chapter</p><h3>{trip.length ? `${trip.length} place${trip.length > 1 ? 's' : ''} in your trip` : 'A trip made around you'}</h3><p>Tell us what makes a good day, and we&apos;ll map the rest.</p></div></div><button className="outline-button" onClick={() => setShowPrefs(true)}>{trip.length ? 'Shape this trip' : 'Find my places'} <ArrowRight size={16} /></button></div></section>

      {selected && <div className="modal-backdrop" role="presentation" onClick={() => setSelected(null)}><div className="place-modal" role="dialog" aria-modal="true" aria-label={selected.name} onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close"><X size={18} /></button><img src={selected.image} alt={selected.name} /><div className="modal-content"><p className="eyebrow">{selected.type} · {selected.distance} from you</p><h2>{selected.name}</h2><p>{selected.blurb}</p><div className="modal-tags">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><button className="dark-button full" onClick={() => toggleTrip(selected.id)}>{trip.includes(selected.id) ? <><Check size={16} /> Added to your trip</> : <><Plus size={16} /> Add to my trip</>}</button></div></div></div>}
      {showPrefs && <div className="modal-backdrop" role="presentation" onClick={() => setShowPrefs(false)}><div className="prefs-modal" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setShowPrefs(false)} aria-label="Close"><X size={18} /></button><span className="trip-icon"><Heart size={17} /></span><p className="eyebrow">Your compass</p><h2>What makes a good day?</h2><p>Choose a few signals and we&apos;ll tune your map to you.</p><div className="preference-options">{['Quiet & unhurried', 'Eat something local', 'Get lost in nature', 'Meet the makers'].map((item) => <button key={item} onClick={(e) => e.currentTarget.classList.toggle('selected')}><span>{item}</span><Check size={15} /></button>)}</div><button className="dark-button full" onClick={() => { setShowPrefs(false); notify('Your compass is ready') }}>Show me the way <ArrowRight size={16} /></button></div></div>}
      {toast && <div className="toast"><Check size={15} /> {toast}</div>}
      <footer><span className="brand"><span className="brand-mark"><Compass size={16} /></span> hidden<span className="brand-accent">india</span></span><span>Go gently. Look closer.</span><span>© 2026 Hidden India</span></footer>
    </main>
  )
}
